# Generated by Django 3.2.6 on 2023-07-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokersite', '0002_auto_20230716_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='minutes',
            new_name='hours',
        ),
    ]
